## Synthetic population pipeline for Île-de-France
## based on the synpp package

# This is the path to a directory where the pipeline can store temporary data
working_directory: /home/dialloaziseoumar/AziseThesis/GenerationPopulationSynthetique/lille_metropolis/cache

# This section defines which parts of the pipeline should be run
run:
  - synthesis.output # To create the output population in the output_path (see below)
  - matsim.output # Uncomment, if you want to run the full simulation (you'll need Java for that)

# Here the configuraiton of the pipeline starts
config:
  # Some general configuration
  processes: 4

  # Define whether to use ENTD or EGT or EMD as the household travel survey (HTS)
  hts: emd

  # Define sampling rate and random seed for the output population
  sampling_rate: 1
  random_seed: 1234

  # Paths to the input data and where the output should be stored
  data_path: /home/dialloaziseoumar/AziseThesis/GenerationPopulationSynthetique/mel/data
  output_path: /home/dialloaziseoumar/AziseThesis/GenerationPopulationSynthetique/lille_metropolis/output

  # Only interesting if you run the simulation
  java_memory: 14G
